name: postgresql96-pgpool2-36
version: 3.6.0
summary: pgpool-II is a connection pooler for PostgreSQL.
description: pgpool-II is a middleware that works between PostgreSQL servers and a PostgreSQL database client.
             It is licensed under BSD license. It provides the following features – Connection Pooling, Replication
             Load Balancing, Limiting Exceeding Connections.
confinement: strict #or devmode
grade: stable

apps:
  pgpool:
      command: usr/bin/pgpool
      plugs:
        - network
        - network-bind
  pgpool-setup:
      command: usr/bin/pgpool_setup
      plugs:
        - network
  watchdog-setup:
      command: usr/bin/watchdog_setup
      plugs:
        - network
  pcp-attach-node:
      command: usr/bin/pcp_attach_node
      plugs:
        - network
  pcp-detach-node:
      command: usr/bin/pcp_detach_node
      plugs:
        - network
  pcp-node-count:
      command: usr/bin/pcp_node_count
      plugs:
        - network
  pcp-node-info:
      command: usr/bin/pcp_node_info
      plugs:
        - network
  pcp-pool-status:
      command: usr/bin/pcp_pool_status
      plugs:
        - network
  pcp-proc-count:
      command: usr/bin/pcp_proc_count
      plugs:
        - network
  pcp-proc-info:
      command: usr/bin/pcp_proc_info
      plugs:
        - network
  pcp-promote-node:
      command: usr/bin/pcp_promote_node
      plugs:
        - network
  pcp-recovery-node:
      command: usr/bin/pcp_recovery_node
      plugs:
        - network
  pcp-stop-pgpool:
      command: usr/bin/pcp_stop_pgpool
      plugs:
        - network
  pcp-watchdog-info:
      command: usr/bin/pcp_watchdog_info
      plugs:
        - network
  pg-md5:
      command: usr/bin/pg_md5

parts:
  pgpool:
    plugin: autotools
    source: http://www.pgpool.net/download.php?f=pgpool-II-3.6.0.tar.gz
    configflags:
        - --prefix=/usr
        - --localstatedir=/etc
        - --sysconfdir=/var
        - --with-openssl
        - --enable-sequence-lock
        #- --with-pgsql=/usr
        - --with-memcached=/usr
        - --with-pam
    build-packages:
        - libssl-dev
        - libpq-dev
        - libmemcached-dev
        - libpgpool-dev
        - postgresql-server-dev-9.6
        - libpam0g-dev
    #stage-packages:
    #    - libpgpool0
    install: |
        base=$(pwd)

        # Build pgpool-adm
        cd $base/src/sql/pgpool_adm
        make && make install DESTDIR=$SNAPCRAFT_PART_INSTALL

        # Build pgpool-recovery
        cd $base/src/sql/pgpool-recovery
        make && make install DESTDIR=$SNAPCRAFT_PART_INSTALL

        # Build pgpool-regclass
        cd $base/src/sql/pgpool-regclass
        make && make install DESTDIR=$SNAPCRAFT_PART_INSTALL

